import pandas as pd
import numpy as np
import os

# --- STEP 1: LOAD MASTER DATA ---
script_dir = os.path.dirname(os.path.abspath(__file__))
# Loading the file generated by enrich_data_100.py
input_file = os.path.join(script_dir, "../data/motif_master_data_100.csv")

if not os.path.exists(input_file):
    print(f"❌ Error: {input_file} not found. Run enrich_data_100.py first!")
else:
    print(f"📂 Loading master data from {input_file}...")
    df = pd.read_csv(input_file)

# --- STEP 2: DEFINE YOUR RAG BUILDER (ENHANCED EDITION) ---
def build_narrative_rag(row):
    """
    Constructs a semantic document optimized for Vector Search.
    Now includes rich cast data and asset metadata.
    """
    
    # 🛡️ HELPER: Prevents "nan", "None", or empty entries
    def clean_val(value):
        s = str(value).strip()
        if s.lower() in ['nan', 'none', '', '[]', '0.0', '0']:
            return None
        return s

    # --- 1. THE IDENTITY (High Weight) ---
    title = row.get('title', 'Unknown Title')
    # Support both 'year' or 'release_year' column names
    year_val = clean_val(row.get('release_year')) or clean_val(row.get('year'))
    year = f"({int(float(year_val))})" if year_val else ""
    genres = clean_val(row.get('genres')) or "film"
    director = clean_val(row.get('director'))
    
    identity = f"{title} {year} is a {genres} movie"
    if director:
        identity += f" directed by {director}."
    else:
        identity += "."

    # --- 2. THE SIGNAL (Atmosphere & Plot) ---
    vibe = clean_val(row.get('synthetic_vibe'))
    overview = clean_val(row.get('overview'))
    
    signal = ""
    if vibe: signal += f"Vibe and Cultural Context: {vibe} "
    if overview: signal += f"Plot Summary: {overview}"

    # --- 3. THE RICH ENTITIES (Cast & Crew) ---
    # Now uses the "Actor (as Character)" format from your patch
    people_parts = []
    cast = clean_val(row.get('cast'))
    writer = clean_val(row.get('writer'))
    composer = clean_val(row.get('composer'))
    cinematographer = clean_val(row.get('cinematographer'))

    if cast: people_parts.append(f"Starring: {cast}")
    if writer: people_parts.append(f"Written by: {writer}")
    if composer: people_parts.append(f"Music by: {composer}")
    if cinematographer: people_parts.append(f"Cinematography by: {cinematographer}")
    
    people_str = ". ".join(people_parts) + "." if people_parts else ""

    # --- 4. THE METADATA (Stats & Assets) ---
    meta_parts = []
    tagline = clean_val(row.get('tagline'))
    if tagline: meta_parts.append(f"Tagline: '{tagline}'")

    rating = clean_val(row.get('vote_average'))
    if rating: meta_parts.append(f"TMDB Rating: {float(rating):.1/10}")

    # Adding URLs to the RAG string can help some LLMs "know" they exist, 
    # though usually, we keep these in separate metadata fields in the DB.
    poster = clean_val(row.get('poster_url'))
    if poster: meta_parts.append(f"Poster available at {poster}")

    meta_str = ". ".join(meta_parts) + "." if meta_parts else ""

    # --- COMBINE ---
    # Clear sectioning helps embeddings differentiate between talent and plot.
    final_chunk = f"{identity}\n\n{signal}\n\n{people_str}\n\n{meta_str}"
    
    return " ".join(final_chunk.split())

# --- STEP 3: APPLY & SAVE ---
if 'df' in locals():
    print("📝 Constructing RAG strings with Rich Cast and Assets...")
    df['rag_content'] = df.apply(build_narrative_rag, axis=1)

    output_file = os.path.join(script_dir, "../data/motif_final_rag.csv")
    df.to_csv(output_file, index=False)
    print(f"✅ DONE! RAG Ready CSV saved to {output_file}")
    print("\n--- Example RAG String ---")
    print(df['rag_content'].iloc[0])